/*
 * Example 01: minimal wrapper
 *
 * This is an example that relies on the JS glue generated by Emscripten, and on the minimal custom TypeScript wrapper for it.
 * It shows that there's almost no need for anything else outside of what Emscripten generates, to use ttf2mesh Wasm module.
 */

import * as fs from "fs/promises"
import { getWasmImports } from "a.out.js"
import { createWasmModuleWrapper, WasmModuleWrapper } from "./wasm-wrapper-minimal/wasm-wrapper.js";

let memory: WebAssembly.Memory;

type WasmExports = {
    // ---
    malloc: (amount: number) => number
    // ---
    testJsLog: (n: number) => void
    wasm_loadFontFromBuffer: (dataAddress: number, size: number) => number
    wasm_getGlyphMeshData: (char: number) => number
}

/* The initial start offset for the payload is 4 because the first 4 bytes are the size of the buffer.
 * The size is required to let JS get the memory segment of the returned array */
const PAYLOAD_START_OFFSET = 4;

const GLYPH_ID = 65 /* Unicode for the 'A' letter */

export async function testWasm() {
    const fileBuffer = await fs.readFile("./wasm/a.out.wasm")
    console.log(" -- Wasm fileBuffer=", fileBuffer)
    const imports = getWasmImports() 

    console.log(" --- Wasm Test -- A")
    const program = await WebAssembly.instantiate(fileBuffer, 
        imports
        // {
        //     "env": imports,
        //     // wasi_snapshot_preview1: () => { console.log(arguments) } 
        // }
    )
    console.log(" --- Wasm Test -- B")
    memory = program.instance.exports.memory as WebAssembly.Memory

    const {
        malloc,
        wasm_loadFontFromBuffer,
        wasm_getGlyphMeshData
    } = program.instance.exports as WasmExports

    const wrapper = createWasmModuleWrapper(program)

    const file = await fs.readFile("./wasm/SourceCodePro-Regular.ttf")

    /* info: https://stackoverflow.com/a/67848896 */
    const buffer = new Uint8Array(file.buffer, file.byteOffset, file.length)

    /* As Wasm to allocate a buffer for the font */
    const allocationPointer = malloc(file.length);

    /* Pass the font to Wasm */
    const passBuffer = new Uint8Array(memory.buffer, allocationPointer, buffer.length);    
    passBuffer.set(buffer)

    console.log(" -- Loading font from buffer=", buffer)
    console.log(" -- length=", buffer.length, ", allocation pointer=", allocationPointer, ", offset=", passBuffer.byteOffset)
    
    /* Ask ttf2mesh to load the font from the passed buffer */
    wasm_loadFontFromBuffer(passBuffer.byteOffset, buffer.length)

    /* Ask ttf2mesh to render the glyph data, and get the pointer to the output start */
    const dataStartPointer = wasm_getGlyphMeshData(GLYPH_ID)
    console.log(" --- Wasm Test --- dataStart=", dataStartPointer)

    /* The first 4 bytes of the output are the length of the glyph data buffer */
    const payloadLength = wrapper.getValue(dataStartPointer, "i32") as number
    console.log(" --- Wasm Test --- dataLength=", payloadLength)

    /* Read the payload */
    const payloadStart = dataStartPointer + PAYLOAD_START_OFFSET
    const glyphData = memory.buffer.slice(payloadStart, payloadStart + payloadLength)
    console.log(" --- Wasm Test --- data=", glyphData)

    /* Unpack and use the glyph data */
    unpackGlyphData(wrapper, payloadStart, glyphData)
    // memory.buffer[]
}

type GlyphDataReader = {
    ints: Int32Array
    uints: Uint32Array
    floats: Float32Array
    offset: number
    readInt: (this: GlyphDataReader) => number
    readUint: (this: GlyphDataReader) => number
    readFloat: (this: GlyphDataReader) => number
}

function readInt(this: GlyphDataReader): number {
    const value = this.ints[this.offset]
    this.offset += 1
    return value
}
function readUint(this: GlyphDataReader): number {
    const value = this.uints[this.offset]
    this.offset += 1
    return value
}
function readFloat(this: GlyphDataReader): number {
    const value = this.floats[this.offset]
    this.offset += 1
    return value
}

type T_Vertex = [number, number, number]
type T_Face = [number, number, number]
type T_Normal = [number, number, number]

function unpackGlyphData(wrapper: WasmModuleWrapper, payloadStart: number, data: ArrayBuffer) {
    const r: GlyphDataReader = {
        ints: new Int32Array(data),
        uints: new Uint32Array(data),
        floats: new Float32Array(data),
        offset: 0,
        readInt, readUint, readFloat
    }

    const verts: T_Vertex[] = []
    const faces: T_Face[] = []
    const normals: T_Normal[] = []

    const nvert = r.readInt()
    const nfaces = r.readInt()

    console.log(" --- verts n=", nvert, ", get value=", wrapper.getValue(payloadStart, "i32"), ", prev=", wrapper.getValue(payloadStart - 4, "i32"))
    console.log(" --- faces n=", nfaces)

    // return // for now

    for (let i = 0; i < nvert; i++) {
        const x = r.readFloat()
        const y = r.readFloat()
        const z = r.readFloat()
        verts.push([x, y, z])
    }
    for (let i = 0; i < nfaces; i++) {
        const v1 = r.readInt()
        const v2 = r.readInt()
        const v3 = r.readInt()
        faces.push([v1, v2, v3])
    }
    for (let i = 0; i < nfaces; i++) {
        const x = r.readFloat()
        const y = r.readFloat()
        const z = r.readFloat()
        normals.push([x, y, z])
    }

    console.log(" --- verts=", verts)
    console.log(" --- faces=", faces)
    console.log(" --- normals=", normals)

    const isOutline = r.readInt()
    console.log(" --- is outline=", isOutline)
}