/*
 * Example 02: full wrapper
 *
 * This is example doesn't rely on the JS glue generated by Emscripten, and instead works with the full custom TypeScript Wasm module wrapper.
 * It shows how to use the full wrapper.
 */

import * as fs from "fs/promises"
import { createGlyphDataReader } from "./ttf2mesh.js";
import { createWasmModuleWrapper, WasmModuleWrapper } from "./wasm-wrapper/wasm-wrapper.js";
import { DefaultWasmExports } from "./wasm-wrapper/wasm-wrapper-exports.js";
import { WasmModuleWrapper_InstantiationParams } from "./wasm-wrapper/wasm-wrapper-instance.js";

type T_Vector3 = [number, number, number]

const GLYPH_ID = 65 /* Unicode for the 'A' letter */

type WasmExports = DefaultWasmExports & {
    // ---
    malloc: (amount: number) => number
    free: (pointer: number) => void
    // ---
    testJsLog: (n: number) => void
    wasm_loadFontFromBuffer: (dataAddress: number, size: number) => number
    wasm_getGlyphMeshData: (char: number, quality: number, features: number, depth: number) => number
}

/* The initial start offset for the payload is 4 because the first 4 bytes are the size of the buffer.
 * The size is required to let JS get the memory segment of the returned array */
const PAYLOAD_START_OFFSET = 4;

const TTF_QUALITY_LOW = 10
const TTF_QUALITY_NORMAL = 20
const TTF_QUALITY_HIGH = 50

const TTF_FEATURE_DEFAULT = 0
const TTF_FEATURE_GNORE_ERROR = 1

export async function testWasm() {
    // const fileBuffer = await fs.readFile("./wasm/a.out.wasm")
    // console.log(" -- Wasm fileBuffer=", fileBuffer)

    // const program = await WebAssembly.instantiate(fileBuffer, getWasmImports())

    const params: WasmModuleWrapper_InstantiationParams = {
        // ...
        localFile: {
            relativePath: "./wasm/a.out.wasm",
            readLocalFile: async (relativePath: string) => await fs.readFile(relativePath)
        },
        config: {
            isEmscripten: true
        }
    }

    const wrapper = await createWasmModuleWrapper(params)

    // const fontFilename = "./wasm/DMMono-Regular.ttf"
    const fontFilename = "./wasm/SourceCodePro-Regular.ttf"
    loadFontFromFilename(wrapper, fontFilename)

    getGlyphData(wrapper, GLYPH_ID)
}

async function loadFontFromFilename(wrapper: WasmModuleWrapper, fontFilename: string) {
    const { malloc, wasm_loadFontFromBuffer } = wrapper.instance.getExports<WasmExports>()
    const file = await fs.readFile(fontFilename)

    /* info: https://stackoverflow.com/a/67848896 */
    const buffer = new Uint8Array(file.buffer, file.byteOffset, file.length)

    /* "wp" for "Wasm pointer" */
    const wp_fontFile = malloc(file.length);

    const passBuffer = new Uint8Array(wrapper.memory.getMemory().buffer, wp_fontFile, buffer.length);    
    passBuffer.set(buffer)

    console.log(` -- Loading font='${fontFilename}': buffer length=${buffer.length}, pointer=${wp_fontFile}, offset=${passBuffer.byteOffset}`)
    wasm_loadFontFromBuffer(passBuffer.byteOffset, buffer.length)
}

function getGlyphData(wrapper: WasmModuleWrapper, glyph: number) {
    const { free, wasm_getGlyphMeshData } = wrapper.instance.getExports<WasmExports>()

    const depth = 0.1
    const dataStart = wasm_getGlyphMeshData(glyph, TTF_QUALITY_NORMAL, TTF_FEATURE_DEFAULT, depth)
    console.log(" --- Wasm Test --- dataStart=", dataStart)

    const payloadLength = wrapper.memory.getValue(dataStart, "i32") as number
    console.log(" --- Wasm Test --- dataLength=", payloadLength)

    const payloadStart = dataStart + PAYLOAD_START_OFFSET
    const data = wrapper.memory.getMemory().buffer.slice(payloadStart, payloadStart + payloadLength)
    console.log(" --- Wasm Test --- data=", data)

    unpackGlyphData(wrapper, payloadStart, data)

    free(dataStart)
}

function unpackGlyphData(wrapper: WasmModuleWrapper, payloadStart: number, data: ArrayBuffer) {

    const r = createGlyphDataReader(data)

    const verts: T_Vector3[] = []
    const faces: T_Vector3[] = []
    const normals: T_Vector3[] = []

    const nvert = r.readInt()
    const nfaces = r.readInt()

    console.log(" --- verts n=", nvert, ", get value=", wrapper.memory.getValue(payloadStart, "i32"), ", prev=", wrapper.memory.getValue(payloadStart - 4, "i32"))
    console.log(" --- faces n=", nfaces)

    for (let i = 0; i < nvert; i++) {
        const x = r.readFloat()
        const y = r.readFloat()
        const z = r.readFloat()
        const v: T_Vector3 = [x, y, z]
        verts.push(v)
    }
    for (let i = 0; i < nfaces; i++) {
        const v1 = r.readInt()
        const v2 = r.readInt()
        const v3 = r.readInt()
        const v: T_Vector3 = [v1, v2, v3]
        faces.push(v)
    }
    for (let i = 0; i < nfaces; i++) {
        const x = r.readFloat()
        const y = r.readFloat()
        const z = r.readFloat()
        const v: T_Vector3 = [x, y, z]
        normals.push(v)
    }

    console.log(" --- verts=", verts)
    console.log(" --- faces=", faces)
    console.log(" --- normals=", normals)


    const isOutline = r.readInt()
    console.log(" --- is outline=", isOutline)

    // TODO: Process the outline
    
    return { verts, faces, normals }
}